buildscript {
    repositories {
        maven { url 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'idea'
apply plugin: 'maven-publish'
apply plugin: 'java'

version = '0.1.0'
group = 'com.mahghuuuls.mahzenutils'
archivesBaseName = 'mahzenutils'
sourceCompatibility = 1.8
targetCompatibility = 1.8

minecraft {
    version  = '1.12.2-14.23.5.2847'
    mappings = 'snapshot_20171003'
    runDir   = 'run'
}

repositories {
    mavenCentral()
    maven { url 'https://maven.blamejared.com' }
    maven { url 'https://cursemaven.com' }
}

dependencies {
    deobfCompile "CraftTweaker2:CraftTweaker2-MC1120-Main:1.12-4.1.20.709"
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", "1.12.2"

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': '1.12.2'
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes(
                'Implementation-Title': archivesBaseName,
                'Implementation-Version': version
        )
    }
}